package com.example.galize.model

/**
 * Represents the three choices generated by AI for the user.
 */
data class ChoiceResult(
    val pureHeart: Choice,
    val chaos: Choice,
    val philosopher: Choice,
    val subtext: String = "",       // Decoded subtext of the other party's message
    val affinityDelta: Int = 0      // -10 to +10, how much affinity changes
)

data class Choice(
    val text: String,
    val description: String = "",   // Brief explanation of the choice's effect
    val type: ChoiceType
)

enum class ChoiceType {
    PURE_HEART,
    CHAOS,
    PHILOSOPHER
}
